spring:
  datasource:
    url: jdbc:mysql://54.180.147.12:3306/tomy_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: appuser
    password: "Tmp12345db!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

logging:
  level:
    root: INFO
    com.tomy: INFO
