spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tomy_db}
    username: ${DB_USER:tomy_app}
    password: ${DB_PASS:StrongPass!123}
  flyway:
    clean-on-validation-error: false
    clean-disabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
jwt:
  secret: ${jwt_KEY}
  expiration-time: 86400000 # 24 hours in milliseconds

# OpenAI API Key
openai:
  api:
    key: ${OPENAI_API_KEY}


# Google Cloud Vision API Credentials
gcp:
  vision:
    credentials: ${GCP_VISION_CREDENTIALS:file:/home/ec2-user/keys/gcp-vision.json}

server:
  port: 8080