spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tomy_db}
    username: ${DB_USER:tomy_app}
    password: ${DB_PASS:StrongPass!123}
  flyway:
    clean-on-validation-error: true
    clean-disabled: false
    validate-on-migrate: false
    locations: classpath:db/migration
jwt:
  secret: aF9zZWNyZXRfa2V5X2Zvcl9KV1RfSE1BQ19zaGEyNTZfYWxnb3JpdGhtX2lzX2F0X2xlYXN0XzMyX2J5dGVzX2xvbmc=
  expiration-time: 86400000 # 24 hours in milliseconds

# OpenAI API Key
openai:
  api:
    key: ${OPENAI_API_KEY}


# Google Cloud Vision API Credentials
gcp:
  vision:
    credentials: "file:C:/Users/effor/.key/enduring-sign-436506-t5-baea74924a88.json"