server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://54.180.147.12:3306/tomy_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=utf8}
    username: ${DB_USER:prod_user}
    password: ${DB_PASS:Hf7!Qv2@zL9#Rm4$Xp}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none       # 운영은 Flyway 단독 관리 권장
    show-sql: false
  flyway:
    validate-on-migrate: true
    clean-disabled: true   # 운영에서 clean 금지
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.tomy: INFO
