spring:
  datasource:
    url: jdbc:mysql://prod_db_host:3306/tomy_prod_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: <your_prod_username>
    password: <your_prod_password>
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.tomy: INFO
